veido_dector_node: 
  ros__parameters:
    circularity_thresh: 0.70              # 圆形度阈值
    aim_area: 200                         # 目标面积
    LIGHT_RADIUS: 0.03                    # 目标半径，单位m
    mass: 0.02                            # 物体质量 (kg)*
    area: 0.0001                           # 迎风面积 (m^2)*
    cd: 0.3                               # 风阻系数
    rho: 1.225                            # 空气密度 (kg/m^3)
    g: 9.80665                            # 重力加速度 (m/s^2)
    dt: 0.001                             # 积分时间步长
    tolerance: 0.005                      # 误差容忍度 (m)
    max_possible_v0: 200.0                 # 发射机构能达到的最大初速度 (m/s)*
    K: 0.00091875                         # 阻力系数 K = (0.5 * config.rho * config.cd * config.area) / config.mass *